### PR TITLE
[oauth] use updated oauth flow for refresh_token retrieval

### LINKED ISSUE #2: Not working due to security issue after entering email address.
When beginning the auth flow, getting an error saying, "`Google couldn’t confirm this attempt to sign in is safe. If you think this is a mistake, you can close and try again to sign in.`". This happens with and without the headers, and in the web version and the chrome version.

Unable to resolve.

Screen Shot 2022-09-06 at 2 18 34 PM

### PR DESCRIPTION
**Pull request by r3pwn**
This PR fixes #2 by updating the oauth flow to use newer endpoints

### CODE REVIEW

**Comment by AngeloD2022** [comment]
I have not tested this yet, but out of curiosity, how did you find these new endpoints?

**Comment by r3pwn** [comment]
@AngeloD2022 I noticed that a project called "hangups" (a third-party Hangouts client) also retrieves a refresh_token using the same client ID, but using different (and I can only assume newer) endpoints, with a slightly different flow.

https://github.com/tdryer/hangups

**Comment by AngeloD2022** [comment]
Tested and it works! Thanks for the PR.

**Comment by AngeloD2022** [comment]
@r3pwn I just wanted to let you know that I moved extended contribution credits to README.md. I just wanted a dedicated place for contributor recognition so that the extension view does not become cluttered with future contributor names. I hope you understand my decision. Thank you for your work!!

**Pull request merged**
